package com.skillforge.backend.enums;

public enum NotificationType {

    INSTRUCTOR_REGISTERED,
    INSTRUCTOR_APPROVED,

    COURSE_SUBMITTED,
    COURSE_APPROVED,
    COURSE_REJECTED,

    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    ENROLLMENT_CONFIRMED,

    CERTIFICATE_ISSUED,

    LIVE_SESSION_REQUESTED,
    LIVE_SESSION_APPROVED,
    LIVE_SESSION_REJECTED,
    LIVE_SESSION_CANCELLED,
    LIVE_SESSION_REMINDER,

    ANNOUNCEMENT,
    
    ASSIGNMENT_PUBLISHED,
    ASSIGNMENT_SUBMITTED,
    ASSIGNMENT_EVALUATED
}